try:
    from ez_setup import use_setuptools
    use_setuptools()
except ImportError:
    pass #Is installing from a source package is not copied locally
from setuptools import setup, find_packages

from itteco import __package__, __version__

setup(
    name=__package__,
    version=__version__,
    author='Itteco.com',
    url='http://www.itteco.com/',
    description='Itteco Trac Plugin.',
    license='MIT',
    packages=find_packages(),
    package_data = {
        'itteco': [
            'templates/*',
            'htdocs/charts/amstock/amstock.swf',
            'htdocs/css/*.css',
            'htdocs/css/jquery.ui/themes/flora/*.css',
            'htdocs/css/jquery.ui/themes/flora/i/*',
            'htdocs/images/*',
            'htdocs/isomorphic/login/*',
            'htdocs/isomorphic/skins/Enterprise/images/AdvancedFilter/*',
            'htdocs/isomorphic/skins/Enterprise/images/Backgrounds/*',
            'htdocs/isomorphic/skins/Enterprise/images/ColorPicker/*',
            'htdocs/isomorphic/skins/Enterprise/images/CubeGrid/*',
            'htdocs/isomorphic/skins/Enterprise/images/DatabaseBrowser/*',
            'htdocs/isomorphic/skins/Enterprise/images/DateChooser/*',
            'htdocs/isomorphic/skins/Enterprise/images/Dialog/*',
            'htdocs/isomorphic/skins/Enterprise/images/DynamicForm/*',
            'htdocs/isomorphic/skins/Enterprise/images/FileBrowser/*',
            'htdocs/isomorphic/skins/Enterprise/images/ImgButton/*',
            'htdocs/isomorphic/skins/Enterprise/images/ListGrid/*',
            'htdocs/isomorphic/skins/Enterprise/images/Menu/*',
            'htdocs/isomorphic/skins/Enterprise/images/MultiUploadItem/*',
            'htdocs/isomorphic/skins/Enterprise/images/Progressbar/*',
            'htdocs/isomorphic/skins/Enterprise/images/RecordEditor/*',
            'htdocs/isomorphic/skins/Enterprise/images/RichTextEditor/*',
            'htdocs/isomorphic/skins/Enterprise/images/SchemaViewer/*',
            'htdocs/isomorphic/skins/Enterprise/images/Scrollbar/*',
            'htdocs/isomorphic/skins/Enterprise/images/SectionHeader/*',
            'htdocs/isomorphic/skins/Enterprise/images/Slider/*',
            'htdocs/isomorphic/skins/Enterprise/images/Splitbar/*',
            'htdocs/isomorphic/skins/Enterprise/images/Stretchbar/*',
            'htdocs/isomorphic/skins/Enterprise/images/Tab/bottom/*',
            'htdocs/isomorphic/skins/Enterprise/images/Tab/left/*',
            'htdocs/isomorphic/skins/Enterprise/images/Tab/right/*',
            'htdocs/isomorphic/skins/Enterprise/images/Tab/top/*',
            'htdocs/isomorphic/skins/Enterprise/images/TabSet/*',
            'htdocs/isomorphic/skins/Enterprise/images/ToolStrip/*',
            'htdocs/isomorphic/skins/Enterprise/images/TreeGrid/*',
            'htdocs/isomorphic/skins/Enterprise/images/Window/*',
            'htdocs/isomorphic/skins/Enterprise/images/actions/*',
            'htdocs/isomorphic/skins/Enterprise/images/*.gif',
            'htdocs/isomorphic/skins/Enterprise/images/button/*',
            'htdocs/isomorphic/skins/Enterprise/images/common/*',
            'htdocs/isomorphic/skins/Enterprise/images/controls/*',
            'htdocs/isomorphic/skins/Enterprise/images/cssButton/*',
            'htdocs/isomorphic/skins/Enterprise/images/edges/*.gif',
            'htdocs/isomorphic/skins/Enterprise/images/edges/*.png',
            'htdocs/isomorphic/skins/Enterprise/images/edges/rounded/frame/A3B2CC/*',
            'htdocs/isomorphic/skins/Enterprise/images/edges/rounded/frame/FFFFFF/*',
            'htdocs/isomorphic/skins/Enterprise/images/edges/rounded/raised/FFFFFF/*',
            'htdocs/isomorphic/skins/Enterprise/images/edges/square/frame/FFFFFF/*',
            'htdocs/isomorphic/skins/Enterprise/images/edges/square/frame/tint/*',
            'htdocs/isomorphic/skins/Enterprise/images/edges/square/raised/FFFFFF/*',
            'htdocs/isomorphic/skins/Enterprise/images/edges/square/raised/tint/*',
            'htdocs/isomorphic/skins/Enterprise/images/shared/*.gif',
            'htdocs/isomorphic/skins/Enterprise/images/shared/*.png',
            'htdocs/isomorphic/skins/Enterprise/images/shared/shadows/*',
            'htdocs/isomorphic/skins/Enterprise/*.js',
            'htdocs/isomorphic/skins/Enterprise/*.js.gz',
            'htdocs/isomorphic/skins/Enterprise/*.css',
            'htdocs/isomorphic/skins/Enterprise/*.css.gz',
            'htdocs/isomorphic/skins/Enterprise/*.html',
            'htdocs/isomorphic/system/modules/*.js',
            'htdocs/js/*.js',
            'htdocs/js/jquery.ui/*.js'
        ],
        'itteco.config': ['sample.ini']
    },
    entry_points = {
        'trac.plugins': ['itteco.init = itteco.init',
        'itteco.scrum.api = itteco.scrum.api',
        'itteco.scrum.web_ui = itteco.scrum.web_ui',
        'itteco.scrum.burndown = itteco.scrum.burndown',
        'itteco.ticket.admin = itteco.ticket.admin',
        'itteco.ticket.report = itteco.ticket.report',
        'itteco.ticket.roadmap = itteco.ticket.roadmap',
        'itteco.ticket.web_ui = itteco.ticket.web_ui',
        'itteco.calendar.web_ui = itteco.calendar.web_ui']
    },
    install_requires=['trac >= 0.11.3','genshi >= 0.5.1'], 
)